import {
  FIND_USER,
  EDIT_USER_INFO
} from './User/user';
import {
  FIND_RESERVATION,
  GET_DASHBOARD_COUNT
} from "./Reservation/reservation";
import {
  FIND_PRODUCT,
  LIKE_PRODUCT,
  GET_REVIEW_LIST_OF_PRODUCT,
  GET_PRODUCT_RESERVATION
} from './Product/product';
import FIND_NOTICE from './Notice/notice';
import FIND_REVIEW from './Review/review';
import {
  FIND_HOSPITAL,
  GET_HOSPITAL_RESERVATION_INFO,
  GET_HOSPITAL_PRODUCT_LIST
} from './Hospital/hospital';
import FIND_HOSPITAL_ADMIN from './HospitalAdmin/hospitalAdmin';
import {
  GET_BANNER_LIST,
  GET_BANNER_FROM_PRODUCT
} from './Banner/banner';
import {
  GET_PAYMENT
} from './Payment/payment';

export {
  FIND_USER,
  EDIT_USER_INFO,
  FIND_RESERVATION,
  GET_DASHBOARD_COUNT,
  FIND_PRODUCT,
  FIND_NOTICE,
  LIKE_PRODUCT,
  GET_REVIEW_LIST_OF_PRODUCT,
  GET_PRODUCT_RESERVATION,
  FIND_REVIEW,
  FIND_HOSPITAL,
  GET_HOSPITAL_RESERVATION_INFO,
  GET_HOSPITAL_PRODUCT_LIST,
  FIND_HOSPITAL_ADMIN,
  GET_BANNER_LIST,
  GET_BANNER_FROM_PRODUCT,
  GET_PAYMENT
};
