// query

//user
export const REQUEST_GET_USERINFO = 'REQUEST_GET_USERINFO';
export const SUCCESS_GET_USERINFO = 'SUCCESS_GET_USERINFO';

export const REQUEST_GET_PRODUCTS = 'REQUEST_GET_PRODUCTS';
export const SUCCESS_GET_PRODUCTS = 'SUCCESS_GET_PRODUCTS';

export const REQUEST_GET_RESERVATIONS = 'REQUEST_GET_RESERVATIONS';
export const SUCCESS_GET_RESERVATIONS = 'SUCCESS_GET_RESERVATIONS';

export const REQUEST_GET_LIKEPRODUCTS = 'REQUEST_GET_LIKEPRODUCTS';
export const SUCCESS_GET_LIKEPRODUCTS = 'SUCCESS_GET_LIKEPRODUCTS';

export const REQUEST_GET_HOSPITAL = 'REQUEST_GET_HOSPITAL';
export const SUCCESS_GET_HOSPITAL = 'SUCCESS_GET_HOSPITAL';

export const REQUEST_GET_HOSPITALADMIN = 'REQUEST_GET_HOSPITALADMIN';
export const SUCCESS_GET_HOSPITALADMIN = 'SUCCESS_GET_HOSPITALADMIN';

export const REQUEST_GET_NOTICES = 'REQUEST_GET_NOTICES';
export const SUCCESS_GET_NOTICES = 'SUCCESS_GET_NOTICES';

export const REQUEST_GET_BANNERS = 'REQUEST_GET_BANNERS';
export const SUCCESS_GET_BANNERS = 'SUCCESS_GET_BANNERS';

export const REQUEST_GET_EVENTS = 'REQUEST_GET_EVENTS';
export const SUCCESS_GET_EVENTS = 'SUCCESS_GET_EVENTS';

export const REQUEST_GET_PAYMENT = 'REQUEST_GET_PAYMENT';
export const SUCCESS_GET_PAYMENT = 'SUCCESS_GET_PAYMENT';

// mutation

export const REQUEST_ADD_RESERVATION = 'REQUEST_ADD_RESERVATION';
export const SUCCESS_ADD_RESERVATION = 'SUCCESS_ADD_RESERVATION';

export const REQUEST_ADD_REVIEW = 'REQUEST_ADD_REVIEW';
export const SUCCESS_ADD_REVIEW = 'SUCCESS_ADD_REVIEW';

export const REQUEST_ADD_USERINFO = 'REQUEST_ADD_USERINFO';
export const SUCCESS_ADD_USERINFO = 'SUCCESS_ADD_USERINFO';

export const REQUEST_ADD_LIKEPRODUCTS = 'REQUEST_ADD_LIKEPRODUCTS';
export const SUCCESS_ADD_LIKEPRODUCTS = 'SUCCESS_ADD_LIKEPRODUCTS';

export const REQUEST_MODIFY_RESERVATION = 'REQUEST_MODIFY_RESERVATION';
export const SUCCESS_MODIFY_RESERVATION = 'SUCCESS_MODIFY_RESERVATION';

export const REQUEST_FIX_RESERVATION = 'REQUEST_FIX_RESERVATION';
export const SUCCESS_FIX_RESERVATION = 'SUCCESS_FIX_RESERVATION';

export const REQUEST_DEL_RESERVATION = 'REQUEST_DEL_RESERVATION';
export const SUCCESS_DEL_RESERVATION = 'SUCCESS_DEL_RESERVATION';

export const REQUEST_CONFIRM_PURCHASE = 'REQUEST_CONFIRM_PURCHASE';
export const SUCCESS_CONFIRM_PURCHASE = 'SUCCESS_CONFIRM_PURCHASE';

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const SUCCESS_ADD_USER = 'SUCCESS_ADD_USER';

export const REQUEST_ADD_NOTICE = 'REQUEST_ADD_NOTICE';
export const SUCCESS_ADD_NOTICE = 'SUCCESS_ADD_NOTICE';

export const REQUEST_ADD_BANNER = 'REQUEST_ADD_BANNER';
export const SUCCESS_ADD_BANNER = 'SUCCESS_ADD_BANNER';

export const REQUEST_ADD_HOSPITALADMIN = 'REQUEST_ADD_HOSPITALADMIN';
export const SUCCESS_ADD_HOSPITALADMIN = 'SUCCESS_ADD_HOSPITALADMIN';

export const REQUEST_ADD_EVENT = 'REQUEST_ADD_EVENT';
export const SUCCESS_ADD_EVENT = 'SUCCESS_ADD_EVENT';
