// query

export const REQUEST_GET_PRODUCTS = 'REQUEST_GET_PRODUCTS';
export const SUCCESS_GET_PRODUCTS = 'SUCCESS_GET_PRODUCTS';

export const REQUEST_GET_RESERVATIONS = 'REQUEST_GET_RESERVATIONS';
export const SUCCESS_GET_RESERVATIONS = 'SUCCESS_GET_RESERVATIONS';

export const REQUEST_GET_LIKEPRODUCTS = 'REQUEST_GET_LIKEPRODUCTS';
export const SUCCESS_GET_LIKEPRODUCTS = 'SUCCESS_GET_LIKEPRODUCTS';

export const REQUEST_GET_USERINFO = 'REQUEST_GET_USERINFO';
export const SUCCESS_GET_USERINFO = 'SUCCESS_GET_USERINFO';

export const REQUEST_GET_HOSPITAL = 'REQUEST_GET_HOSPITAL';
export const SUCCESS_GET_HOSPITAL = 'SUCCESS_GET_HOSPITAL';

export const REQUEST_GET_HOSPITALADMIN = 'REQUEST_GET_HOSPITALADMIN';
export const SUCCESS_GET_HOSPITALADMIN = 'SUCCESS_GET_HOSPITALADMIN';

export const REQUEST_GET_NOTICES = 'REQUEST_GET_NOTICES';
export const SUCCESS_GET_NOTICES = 'SUCCESS_GET_NOTICES';

export const REQUEST_GET_BANNERS = 'REQUEST_GET_BANNERS';
export const SUCCESS_GET_BANNERS = 'SUCCESS_GET_BANNERS';

// mutation

export const REQUEST_ADD_RESERVATION = 'REQUEST_ADD_RESERVATION';
export const SUCCESS_ADD_RESERVATION = 'SUCCESS_ADD_RESERVATION';

export const REQUEST_ADD_REVIEW = 'REQUEST_ADD_REVIEW';
export const SUCCESS_ADD_REVIEW = 'SUCCESS_ADD_REVIEW';

export const REQUEST_ADD_USERINFO = 'REQUEST_ADD_USERINFO';
export const SUCCESS_ADD_USERINFO = 'SUCCESS_ADD_USERINFO';

export const REQUEST_ADD_LIKEPRODUCTS = 'REQUEST_ADD_LIKEPRODUCTS';
export const SUCCESS_ADD_LIKEPRODUCTS = 'SUCCESS_ADD_LIKEPRODUCTS';

export const REQUEST_MODIFY_RESERVATION = 'REQUEST_MODIFY_RESERVATION';
export const SUCCESS_MODIFY_RESERVATION = 'SUCCESS_MODIFY_RESERVATION';

export const REQUEST_FIX_RESERVATION = 'REQUEST_FIX_RESERVATION';
export const SUCCESS_FIX_RESERVATION = 'SUCCESS_FIX_RESERVATION';

export const REQUEST_CONFIRM_PURCHASE = 'REQUEST_CONFIRM_PURCHASE';
export const SUCCESS_CONFIRM_PURCHASE = 'SUCCESS_CONFIRM_PURCHASE';

export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const SUCCESS_ADD_USER = 'SUCCESS_ADD_USER';
