export const REQUEST_PRODUCTS_LIST = 'REQUEST_PRODUCTS_LIST';
export const SUCCESS_PRODUCTS_LIST = 'SUCCESS_PRODUCTS_LIST';

// 마이페이지
export const REQUEST_RESERVATIONS_LIST = 'REQUEST_RESERVATION_LIST';
export const SUCCESS_RESERVATIONS_LIST = 'SUCCESS_RESERVATION_LIST';

export const REQUEST_LIKEPRODUCTS_LIST = 'REQUEST_LIKEPRODUCTS_LIST';
export const SUCCESS_LIKEPRODUCTS_LIST = 'SUCCESS_LIKEPRODUCTS_LIST';

export const REQUEST_EDIT_INFO = 'REQUEST_EDIT_INFO';
export const SUCCESS_EDIT_INFO = 'SUCCESS_EDIT_INFO';
